### ISSUE TITLE
Latest build from Woolys is 70.0.3538.77 while tap has 70.0.3538.67

### ISSUE THREAD

**Issue by dnivi3** [cpbotha/homebrew-marmaduke-chromium#1]
Latest marmaduke-build is 70.0.3538.77 according to [Woolys](https://chromium.woolyss.com/#mac-64-bit) and the [marmaduke chrome repository](https://github.com/macchrome/macstable/releases/tag/v70.0.3538.77-r587811-macOS).

Thanks for creating and maintaining this homebrew tap!

**Comment by cpbotha** [comment]
Thank you very much for letting me know.

Fixed in commit bd4fa300db3d6a7912f20404986f425e82ddba86
