### ISSUE TITLE
ungoogled-chromium

### ISSUE THREAD

**Issue by dominiklang** [cpbotha/homebrew-marmaduke-chromium#4]
Hi, would it be possible to add the build of marmadukes ungoogled-chromium to this cask?
Best Regards, Dominik

**Comment by SheinH** [comment]
@dominiklangofc It's already in homebrew under `eloston-chromium`.
BTW, ungoogled-chromium is made by eloston not marmaduke.

**Comment by dominiklang** [comment]
I know that ungoogled-chromium is made by eloston, but marmaduke added the widevine plugin: https://chromium.woolyss.com/

**Comment by SheinH** [comment]
@dominiklangofc If you're interested, I'm maintaining my own fork of the marmaduke chromium builds with added dev and ungoogled versions

https://github.com/SheinH/homebrew-marmaduke-chromium

It appears that the maintainer may have abandoned this repo

**Comment by dominiklang** [comment]
> @dominiklangofc If you're interested, I'm maintaining my own fork of the marmaduke chromium builds with added dev and ungoogled versions
> 
> https://github.com/SheinH/homebrew-marmaduke-chromium
> 
> It appears that the maintainer may have abandoned this repo

@SheinH that's exactly what i was looking for. Thank your very much! :-)
