### ISSUE TITLE
Latest build from macchrome is 72.0.3626.109 while tap has 72.0.3626.81

### ISSUE THREAD

**Issue by nnhien** [cpbotha/homebrew-marmaduke-chromium#8]
Latest release is here: https://github.com/macchrome/macstable/releases/tag/v72.0.3626.109-r612437-Ungoogled-macOS

**Comment by cpbotha** [comment]
Sorry about that. Casks have just been updated to 72.0.3626.121.

Also, I've added a cask for Marmaduke's ungoogled build of chromium.
